<?php

namespace App\Filament\Resources;

use App\Filament\Imports\ClassesImporter;
use App\Filament\Resources\ClassesResource\Pages;
use App\Helpers\ExportColumnHelper;
use App\Models\Classes;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Actions\ImportAction;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use pxlrbt\FilamentExcel\Actions\Tables\ExportAction;
use pxlrbt\FilamentExcel\Actions\Tables\ExportBulkAction;
use pxlrbt\FilamentExcel\Exports\ExcelExport;

class ClassesResource extends Resource
{
    protected static ?string $model = Classes::class;

    protected static ?string $navigationGroup = 'Manajemen Data';

    protected static ?string $navigationLabel = 'Data Kelas';

    protected static ?string $label = 'Data Kelas';

    protected static ?string $navigationIcon = 'heroicon-o-building-library';

    protected static ?int $navigationSort = 3;

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->with(['homeroomTeacher']); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->label('Nama')
                    ->required(),
                Forms\Components\TextInput::make('level')
                    ->required()
                    ->numeric()
                    ->required()
                    ->label('Kelas'),
                Forms\Components\TextInput::make('major')
                    ->required()
                    ->required()
                    ->label('Jurusan'),
                Forms\Components\Select::make('homeroom_teacher_nip')
                    ->relationship('homeroomTeacher', 'name')
                    ->required()
                    ->searchable()
                    ->preload()
                    ->label('Wali Kelas'),

            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable()
                    ->label('Nama Kelas')
                    ->sortable(),
                Tables\Columns\TextColumn::make('level')
                    ->searchable()
                    ->label('Level Kelas')
                    ->sortable(),
                Tables\Columns\TextColumn::make('major')
                    ->label('Jurusan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('homeroomTeacher.name')
                    ->label('Wali Kelas')
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ])
            ->headerActions([
                Tables\Actions\Action::make('download_template')
                    ->label('Download Template')
                    ->icon('heroicon-o-document-arrow-down')
                    ->color('gray')
                    ->url(route('template.class'))
                    ->openUrlInNewTab(),
                ImportAction::make('import')
                    ->label('Import Data Kelas')
                    ->importer(ClassesImporter::class)
                    ->color('success')
                    ->icon('heroicon-o-arrow-down-tray'),
                ExportAction::make('export')
                    ->label('Export Data Kelas')
                    ->icon('heroicon-o-arrow-up-tray')
                    ->color('info')
                    ->exports([
                        ExcelExport::make('data-kelas')
                            ->withColumns(
                                ExportColumnHelper::getClassColumns()
                            )
                            ->withFilename('Data Kelas.xlsx'),
                    ]),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                    ExportBulkAction::make('export')
                        ->color('info')
                        ->icon('heroicon-o-arrow-up-tray')
                        ->exports([
                            ExcelExport::make('data-kelas')
                                ->withColumns(
                                    ExportColumnHelper::getClassColumns()
                                )
                                ->withFilename('Data Kelas.xlsx'),
                        ]),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListClasses::route('/'),
            'create' => Pages\CreateClasses::route('/create'),
            'view' => Pages\ViewClasses::route('/{record}'),
            'edit' => Pages\EditClasses::route('/{record}/edit'),
        ];
    }
}
